FROM node:10-alpine

WORKDIR /app/

COPY package*.json ./

# RUN apt-get update && apt-get -y install openssl
RUN apk update && apk upgrade --update-cache --available && \
    apk add openssl && \
    rm -rf /var/cache/apk/*

RUN npm install --production

COPY ./ ./

CMD ["npm", "start"]
