//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class GotoServiceRequest : Message
    {
        public const string RosMessageName = "niryo_moveit/GotoService";

        public NiryoMoveitJoints joints_input;
        public Geometry.Pose target_pose;

        public GotoServiceRequest()
        {
            this.joints_input = new NiryoMoveitJoints();
            this.target_pose = new Geometry.Pose();
        }

        public GotoServiceRequest(NiryoMoveitJoints joints_input, Geometry.Pose target_pose)
        {
            this.joints_input = joints_input;
            this.target_pose = target_pose;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(joints_input.SerializationStatements());
            listOfSerializations.AddRange(target_pose.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.joints_input.Deserialize(data, offset);
            offset = this.target_pose.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "GotoServiceRequest: " +
            "\njoints_input: " + joints_input.ToString() +
            "\ntarget_pose: " + target_pose.ToString();
        }
    }
}
