#!/bin/bash
source $ROS_WORKSPACE/devel/setup.bash
echo "ROS_IP: $(hostname -i)" > $ROS_WORKSPACE/src/niryo_moveit/config/params.yaml

# exec "$@"
cd $ROS_WORKSPACE/src/
exec roslaunch niryo_moveit part_3.launch