FROM node:10-alpine

WORKDIR /app/

COPY ./ ./

RUN apk update && apk upgrade --update-cache --available && \
    apk add openssl && \
    rm -rf /var/cache/apk/*

RUN npm install --production && npm run build

RUN rm -rf src types __tests__

EXPOSE 9229

CMD ["npm", "start"]
