export const HTTP_CODE_200 = 200;
export const HTTP_CODE_500 = 500;
export const HTTP_CODE_400 = 400;
export const MODULE_NAME = "DataUpdater";
export const DATA_UPDATE_METHOD_NAME = "DataUpdate"
export const CONFIG_PATH = "/appdata/pn.json";
export const GYROPHARE_DISPLAY_NAME = process.env.GYROPHARE_DISPLAY_NAME || "PLC.InputData"
export const EDGE_UPDATE_NAME = "edgeUpdate"
export const GYROPHARE_BIN_PLACE = parseInt(process.env.GYROPHARE_BIN_PLACE) || 2